version: 2.1

jobs:
  working_directory: ~/mssc-beer-service

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results